name: Sync Swimming Calendar

on:
  schedule:
    # Run weekly on Sundays at 6 AM UTC (1 AM CDT)
    - cron: '0 6 * * 0'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run in dry-run mode (no changes)'
        required: false
        default: 'false'
        type: boolean

jobs:
  sync-calendar:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run calendar sync
      id: sync
      run: |
        if [ "${{ github.event.inputs.dry_run }}" = "true" ]; then
          echo "Running in dry-run mode"
          python sync_calendar.py --dry-run --verbose
        else
          python sync_calendar.py --verbose
        fi
      continue-on-error: true
      
    - name: Check for changes
      id: changes
      run: |
        if git diff --quiet; then
          echo "changes=false" >> $GITHUB_OUTPUT
          echo "No changes detected"
        else
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "Changes detected"
          git diff --stat
        fi
        
    - name: Create Pull Request
      if: steps.changes.outputs.changes == 'true' && github.event.inputs.dry_run != 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: |
          Update swimming calendar from official source
          
          - Synced from wildkitaquatics.com
          - Updated index.html with latest events
          - Updated calendar.ics with latest schedule
          
          🤖 Generated with [Claude Code](https://claude.ai/code)
        title: 'Update swimming calendar from official source'
        body: |
          ## Calendar Update
          
          This PR updates the swimming calendar with the latest information from the official source at wildkitaquatics.com.
          
          ### Changes:
          - ✅ Synced event data from official calendar
          - ✅ Updated HTML calendar display
          - ✅ Updated ICS calendar file
          
          ### Verification:
          - [ ] Check that event count is reasonable
          - [ ] Verify dates and times look correct
          - [ ] Test Google Calendar subscription still works
          - [ ] Check that styling/layout is preserved
          
          This sync was automatically triggered by the scheduled workflow.
          
          🤖 Generated with [Claude Code](https://claude.ai/code)
        branch: calendar-sync-${{ github.run_number }}
        delete-branch: true
        
    - name: Summary
      run: |
        if [ "${{ steps.changes.outputs.changes }}" = "true" ]; then
          if [ "${{ github.event.inputs.dry_run }}" = "true" ]; then
            echo "✅ Dry run completed - changes detected but not committed"
          else
            echo "✅ Calendar sync completed - PR created with updates"
          fi
        else
          echo "✅ Calendar sync completed - no changes needed"
        fi